### ISSUE TITLE
Undefined function '_get_uri'

### ISSUE THREAD

**Issue by warcooft** [michalsn/michalsn.dev#1]
Hi @michalsn,
I really appreciate your good work. 
In this post it seems like there is a section of code/function missing.

[https://github.com/michalsn/michalsn.dev/blob/1003c41bb09b1e675fe8057b0c9b239980990c9b/content/posts/generating-a-custom-domain-links-in-codeigniter-4.md?plain=1#L34](https://github.com/michalsn/michalsn.dev/blob/1003c41bb09b1e675fe8057b0c9b239980990c9b/content/posts/generating-a-custom-domain-links-in-codeigniter-4.md?plain=1#L34) Thanks.

**Comment by michalsn** [comment]
No, the code is correct, but I was using a function marked as internal. And the problem with this type of code is that it likes to disappear.

So in the latest version of the framework, this function no longer exists. I will make an update to this post.

**Comment by warcooft** [comment]
I see, thanks for the update.
